repos:
  - repo: local
    hooks:
      - id: ruff
        name: Run ruff
        entry: make ruff
        language: system
        pass_filenames: false
        always_run: true

      - id: ty
        name: Run type check
        entry: make ty
        language: system
        pass_filenames: false
        always_run: true

      # TODO: Enable tests when they are available
      # - id: test
      #   name: Run tests
      #   entry: make test
      #   language: system
      #   pass_filenames: false
      #   always_run: true
